line-length = 120
indent-width = 4

target-version = "py310"

[lint]
select = ["ALL"]
extend-ignore = [
"D100",
    "ANN101",
    "ANN102",
    "D203",
    "D211",
    "D213",
    "EM101",
    "ERA001",
    "FA102",
    "T201",
    "TRY003",
    "COM812",
    "ISC001",
]

